# Generated by Django 2.0 on 2017-12-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=60)),
                ('builddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateField()),
                ('arrival_time', models.DateField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Airplane')),
                ('arrival_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Airport')),
                ('departure_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('starting_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pilot'),
        ),
    ]
