# Generated by Django 2.0 on 2017-12-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171225_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='pilot_id',
            new_name='pilot',
        ),
    ]
