# Generated by Django 2.0 on 2017-12-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171225_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='builddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
